accounts/urls.py
from django.urls import path,re_path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth import login,logout
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView
app_name = "accounts"

urlpatterns = [
    path('',views.HomeView,name='home'),
    path('data/',views.showall,name='showall'),
    path('login/',auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name="accounts/logout.html"),name='logout'),
    path('register/',views.register,name='register'),
    path('profile/',views.view_profile,name='view_profile'),
    path('profile/edit/',views.edit_profile,name='edit_profile'),
    path('change-password/',views.change_password,name='change_password'),
    
    re_path( r'delete/(?P<pk>\d+)/$', views.tasdelevie.as_view(template_name="accounts/delete.html"),name='delete'),

]

tutorial/urls.py
from django.contrib import admin
from django.urls import path,include
from tutorial import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.login_redirect,name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include(('accounts.urls'))),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
# Create your models here.
from django.db.models.signals import post_save


places = (
('COLLEGE-DANAPUR','COLLEGE-DANAPUR'),
('COLLEGE-PATNA STATION','COLLEGE-PATNA STATION'),
('COLLEGE-PATNA AIRPOR','COLLEGE-PATNA AIRPORT'),
('DANAPUR-COLLEGE','DANAPUR-COLLEGE'),
('PATNA AIRPORT-COLLEGE','PATNA AIRPORT-COLLEGE'),
('PATNA STATION-COLLEGE','PATNA STATION-COLLEGE'),

)

class UserProfileManager(models.Manager):
    pass

#
class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    description = models.CharField(max_length=100,default='')
    city = models.CharField(max_length=100,default='')
    website = models.URLField(default='')
    phone = models.CharField(max_length=10,default=0)
    # image = models.ImageField(upload_to='profile_image',blank=True)

    def __str__(self):
        return self.user.username

def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile,sender=User)


class Post(models.Model):

    fir = models.CharField(max_length=100,default='')

    route = models.CharField(max_length=100,choices=places,default='COLLEGE')
    # person = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    date = models.DateField(null=True)
    time = models.TimeField(null=True)
    phone_no = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # user = models.ForeignKey(User,on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import UserProfile
from accounts.models import Post

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',

            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',

        )

class TravForm(forms.ModelForm):
    # From = forms.CharField(widget=forms.TextInput(
    # attrs={
    #     'class':'form-control',
    #     'placeholder':'write a post....'
    # }
    #
    # ))
    class Meta:
        model = Post
        fields = ('route','date','time','phone_no')

accounts/views.py
from django.shortcuts import render,redirect
from accounts.forms import RegistrationForm,EditProfileForm,TravForm
from accounts.models import Post
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView,View,DeleteView
from django.urls import reverse_lazy
# Create your views here.
# def home(request):
#     numbers = [1,2,3,4,5]
#     name = "Abhishek Nautiyal"
#
#     args = {'myname': name,'numbers': numbers}
#     return render(request,'accounts/home.html',args)

def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:home')
        else:
            args = {'form': form,}
            return render(request, 'accounts/reg_form.html',args)
    else:
        form = RegistrationForm()

        args = {'form': form,}
        return render(request, 'accounts/reg_form.html',args)


@login_required
def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('accounts:view_profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect( 'login')
        else:
            return redirect('/account/change-password')
    else:
        form = PasswordChangeForm(request.user)
        args = {'form': form,}
        return render(request, 'accounts/change_password.html', args)


def HomeView(request):
    template_name = 'accounts/home.html'

    if request.method == 'POST':
        form = TravForm(request.POST)
        if form.is_valid():

            post = form.save(commit=False)
            post.fir = request.user
            post.save()
                # text = form.cleaned_data['post']
                # form = TravForm()
            return redirect('accounts:home')
        else:
            form = TravForm()
            args = {'form': form,}
            return redirect('accounts:view_profile')

    else:
        form = TravForm()
        args = {'form': form,}
        return render(request,'accounts/home.html',args)
    # form_class=TravForm
    # template_name = 'accounts/home.html'

    # def get(self,request):
    #     form = self.form_class(None)
    #     posts = Post.objects.all()
    #     args = {'form':form,'posts':posts}
    #     return render(request,self.template_name,args)
    #
    # def post(self,request):
    #     form = self.form_class(request.POST)
    #     if form.is_valid():
    #         user1 = form.save(commit=False)
    #
    #         route = form.cleaned_data['route']
    #         date = form.cleaned_data['date']
    #         time = form.cleaned_data['time']
    #         phone_no = form.cleaned_data['phone_no']
    #         fir = request.user.username
    #         user1.save()
    #
    #         form = self.form_class()
    #         return redirect('accounts:home')
    #
    #     args = {'form': form,}
    #     return render(request,self.template_name,{'form': form,})

# def remove_items(request):
#     if request.method == 'POST':
#         form = TravForm()
#         posti = Post.objects.all()
#         item_id = (request.POST.get('item_id'))
#         item = Post.objects.get(id=item_id)
#         item.delete()
#         return render(request,'accounts/soh.html',{'posti':posti,})

class tasdelevie(DeleteView):
    model = Post
    template_name = 'accounts/delete.html'
    context_object_name = 'task'
    success_url = reverse_lazy('accounts:showall')

def showall(request):


    posts = Post.objects.all().order_by('-created')
    ans = request.user
    curuser = Post.objects.filter(fir=request.user)
    # curuser = list(curuser)

    notcuruser = Post.objects.exclude(fir=request.user)
    # notcuruser = list(notcuruser)
    # valid_data = list()
    # for x in curuser:
    #     for y in notcuruser:
    #         g = list()
    #         if x.route==y.route and x.date==y.date:
    #              g=g+y
    #     valid_data= valid_data + (g)


    args = {'posts':posts,'curuser':curuser,'notcuruser':notcuruser}
    return render(request,'accounts/soh.html',args)

accounts/templates/accounts/all.html
{% extends 'base.html' %}
  <!-- <h1>Home</h1>
  {% block head %}
  <title>Home</title>
  {% endblock %} -->


  {% block body %}
  <div class="container">

    {% for post in posts %}

      <p>TO {{ post.route }} on  {{ post.date}} at {{ post.time }},phone no {{ post.phone_no }} created on {{ post.created }}</p>

    {% endfor %}
  </div>
  {% endblock %}

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="button">"submit"</button>
    </form>
    <br>
    </div>
{% endblock %}

accounts/templates/accounts/delete.html
{% extends 'base.html' %}
{% block head %}
<title>Delete</title>
{% endblock %}

{% block body %}
<div class="container">
    <form action="" form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete</p>
    <input type="submit" value="delete" />
    </form>
    <br>
    </div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="button">"submit"</button>
    </form>
    <br>
    </div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}
  <!-- <h1>Home</h1>
  {% block head %}
  <title>Home</title>
  {% endblock %} -->


  {% block body %}
  <div class="container">
    <h1>Where U want to go!!</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
    </form>
    <h2>{{ text }}</h2>
    {% for post in posts %}
      <h1>{{ post.post }}</h1>
      <!-- <p></p> -->
      <p1>{{ user }}</p1>
    {% endfor %}
  </div>
  {% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1>Welcome</h1>
<p>
  you can log in here:
</p>
<h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1>Logged Out</h1>
<p>
  you can logged out:
</p>

</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>Website: {{ user.userprofile.website }}</p>
    <!-- <img src="{{ user.userprofile.image.url }}" width="240"> -->
    </div>
{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class = "container">
  <h1>WELCOME</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
  <!-- <h1>Home</h1>
  {% block head %}
  <title>Home</title>
  {% endblock %} -->


  {% block body %}
  <div class="container">
    <h1>Home</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
    </form>
    <h2>{{ text }}</h2>
  </div>
  {% endblock %}

accounts/templates/accounts/soh.html
{% extends 'base.html' %}
  <!-- <h1>Home</h1>
  {% block head %}
  <title>Home</title>
  {% endblock %} -->


  {% block body %}

  <div class="container">

    <table class="table">
           <tr>
               <th>User</th>
               <th>Route</th>
               <th>Date</th>
               <th>Time</th>
               <th>Phone No.</th>
               <th>Delete</th>

               <!-- <th class="col-md-1"></th>
               <th class="col-md-1"></th>
               <th class="col-md-1"></th>
               <th>Away</th> -->
           </tr>


    {% for posti in  curuser %}
    <tr>

      <td>{{ posti.fir }}</td>
      <td>{{ posti.route }}</td>
      <td>{{ posti.date}}</td>
      <td>{{ posti.time }}</td>
      <td>{{ posti.phone_no }}</td>
      <td>
        <a href="{% url 'accounts:delete' posti.id %}">delete</a>
      </td>
    </tr>

    {% endfor %}

    </table>
    <br></br>

    {% for post in  notcuruser %}


      <p>person: {{ post.fir }}TO {{ post.route }} on  {{ post.date}} at {{ post.time }},phone no {{ post.phone_no }} created on {{ post.created }}</p>

    {% endfor %}

    {% for cur in curuser %}

    <table class="table">
        <caption>  {{cur.route}} </caption>
           <tr>
               <th>User</th>
               <th>Route</th>
               <th>Date</th>
               <th>Time</th>
               <th>Phone No.</th>
               <!-- <th class="col-md-1"></th>
               <th class="col-md-1"></th>
               <th class="col-md-1"></th>
               <th>Away</th> -->
           </tr>
           <script>
             var a=1
            </script>
      {% for notcur in notcuruser %}
        {% if  cur.route == notcur.route and cur.date == notcur.date  %}
        <script>
          var a=0
         </script>
        <tr>

          <td>{{ notcur.fir }}</td>
          <td>{{ notcur.route }}</td>
          <td>{{ notcur.date}}</td>
          <td>{{ notcur.time }}</td>
          <td>{{ notcur.phone_no }}</td>
        </tr>
            <!-- <p>TO {{ notcur.route }} on  {{ notcur.date}} at {{ notcur.time }},phone no {{ notcur.phone_no }} created on {{ notcur.created }}</p> -->
        {% endif %}
      {% endfor %}
        </table>
        {% if a == 1 %}
        <p>No data found.</p>
        {% endif %}
    {% endfor %}

  </div>

  {% endblock %}