accounts/urls.py
from django.urls import path,re_path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth import login,logout
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView
app_name = "accounts"

urlpatterns = [
    path('',views.HomeView,name='home'),
    path('data/',views.showall,name='showall'),
    path('login/',auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name="accounts/logout.html"),name='logout'),
    path('register/',views.register,name='register'),
    path('profile/',views.view_profile,name='view_profile'),
    path('profile/edit/',views.edit_profile,name='edit_profile'),
    path('change-password/',views.change_password,name='change_password'),
    
    re_path( r'delete/(?P<pk>\d+)/$', views.tasdelevie.as_view(template_name="accounts/delete.html"),name='delete'),

]

tutorial/urls.py
from django.contrib import admin
from django.urls import path,include
from tutorial import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.login_redirect,name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include(('accounts.urls'))),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
# Create your models here.
from django.db.models.signals import post_save


places = (
('COLLEGE-DANAPUR','COLLEGE-DANAPUR'),
('COLLEGE-PATNA STATION','COLLEGE-PATNA STATION'),
('COLLEGE-PATNA AIRPOR','COLLEGE-PATNA AIRPORT'),
('DANAPUR-COLLEGE','DANAPUR-COLLEGE'),
('PATNA AIRPORT-COLLEGE','PATNA AIRPORT-COLLEGE'),
('PATNA STATION-COLLEGE','PATNA STATION-COLLEGE'),

)

class UserProfileManager(models.Manager):
    pass

#
class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    description = models.CharField(max_length=100,default='')
    city = models.CharField(max_length=100,default='')
    website = models.URLField(default='')
    phone = models.CharField(max_length=10,default=0)
    # image = models.ImageField(upload_to='profile_image',blank=True)

    def __str__(self):
        return self.user.username

def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile,sender=User)


class Post(models.Model):

    fir = models.CharField(max_length=100,default='')

    route = models.CharField(max_length=100,choices=places,default='COLLEGE')
    # person = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    date = models.DateField(null=True)
    time = models.TimeField(null=True)
    phone_no = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # user = models.ForeignKey(User,on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import UserProfile
from accounts.models import Post

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',

            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',

        )

class TravForm(forms.ModelForm):
    # From = forms.CharField(widget=forms.TextInput(
    # attrs={
    #     'class':'form-control',
    #     'placeholder':'write a post....'
    # }
    #
    # ))
    class Meta:
        model = Post
        fields = ('route','date','time','phone_no')

accounts/views.py
from django.shortcuts import render,redirect
from accounts.forms import RegistrationForm,EditProfileForm,TravForm
from accounts.models import Post
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView,View,DeleteView
from django.urls import reverse_lazy
# Create your views here.
# def home(request):
#     numbers = [1,2,3,4,5]
#     name = "Abhishek Nautiyal"
#
#     args = {'myname': name,'numbers': numbers}
#     return render(request,'accounts/home.html',args)

def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:home')
        else:
            args = {'form': form,}
            return render(request, 'accounts/reg_form.html',args)
    else:
        form = RegistrationForm()

        args = {'form': form,}
        return render(request, 'accounts/reg_form.html',args)


@login_required
def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('accounts:view_profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect( 'login')
        else:
            return redirect('/account/change-password')
    else:
        form = PasswordChangeForm(request.user)
        args = {'form': form,}
        return render(request, 'accounts/change_password.html', args)


def HomeView(request):
    template_name = 'accounts/home.html'

    if request.method == 'POST':
        form = TravForm(request.POST)
        if form.is_valid():

            post = form.save(commit=False)
            post.fir = request.user
            post.save()
                # text = form.cleaned_data['post']
                # form = TravForm()
            return redirect('accounts:home')
        else:
            form = TravForm()
            args = {'form': form,}
            return redirect('accounts:view_profile')

    else:
        form = TravForm()
        args = {'form': form,}
        return render(request,'accounts/home.html',args)
    # form_class=TravForm
    # template_name = 'accounts/home.html'

    # def get(self,request):
    #     form = self.form_class(None)
    #     posts = Post.objects.all()
    #     args = {'form':form,'posts':posts}
    #     return render(request,self.template_name,args)
    #
    # def post(self,request):
    #     form = self.form_class(request.POST)
    #     if form.is_valid():
    #         user1 = form.save(commit=False)
    #
    #         route = form.cleaned_data['route']
    #         date = form.cleaned_data['date']
    #         time = form.cleaned_data['time']
    #         phone_no = form.cleaned_data['phone_no']
    #         fir = request.user.username
    #         user1.save()
    #
    #         form = self.form_class()
    #         return redirect('accounts:home')
    #
    #     args = {'form': form,}
    #     return render(request,self.template_name,{'form': form,})

# def remove_items(request):
#     if request.method == 'POST':
#         form = TravForm()
#         posti = Post.objects.all()
#         item_id = (request.POST.get('item_id'))
#         item = Post.objects.get(id=item_id)
#         item.delete()
#         return render(request,'accounts/soh.html',{'posti':posti,})

class tasdelevie(DeleteView):
    model = Post
    template_name = 'accounts/delete.html'
    context_object_name = 'task'
    success_url = reverse_lazy('accounts:showall')

def showall(request):


    posts = Post.objects.all().order_by('-created')
    ans = request.user
    curuser = Post.objects.filter(fir=request.user)
    # curuser = list(curuser)

    notcuruser = Post.objects.exclude(fir=request.user)
    # notcuruser = list(notcuruser)
    # valid_data = list()
    # for x in curuser:
    #     for y in notcuruser:
    #         g = list()
    #         if x.route==y.route and x.date==y.date:
    #              g=g+y
    #     valid_data= valid_data + (g)


    args = {'posts':posts,'curuser':curuser,'notcuruser':notcuruser}
    return render(request,'accounts/soh.html',args)

accounts/templates/base.html
<html>
<head>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
crossorigin="anonymous">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
  {% block head %}
  <title>Base</title>
  {% endblock %}
</head>
<body>
<div>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Cab Share</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        {% if user.is_authenticated %}
        <ul class="nav navbar-nav">
          <!-- <li class="active"><a href="/account">Link <span class="sr-only">(current)</span></a></li> -->
          <li><a href="{% url 'accounts:home' %}">Add_Journey</a></li>

            <li><a href="{% url 'accounts:logout' %}">logout</a></li>
            <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
          <li><a href="{% url 'accounts:edit_profile' %}">EditProfile</a></li>
          <li><a href="{% url 'accounts:change_password' %}">changepasswd</a></li>
          <li><a href="{% url 'accounts:showall' %}">showall</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'accounts:register' %}">Register</a></li>

        </ul>
        {% else %}
        <ul class="nav navbar-nav">
          <!-- <li class="active"><a href="/account">Link <span class="sr-only">(current)</span></a></li> -->
          <li><a href="{% url 'accounts:home' %}">account</a></li>

          <li><a href="{% url 'accounts:login' %}">login</a></li>
            <!-- <li><a href="{% url 'accounts:logout' %}">logout</a></li>
            <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
          <li><a href="{% url 'accounts:edit_profile' %}">EditProfile</a></li>
          <li><a href="{% url 'accounts:change_password' %}">changepasswd</a></li> -->
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'accounts:register' %}">Register</a></li>

        </ul>
        {% endif %}
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>


  {% block body %}
    <h1>Base</h1>
  {% endblock %}
</body>
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
crossorigin="anonymous"></script>
</html>